flags: {}
extra-include-dirs:
- /usr/local/include
- /usr/include
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/lib
- /usr/lib64
packages:
- location:
    git: https://github.com/jaidmin/haskell.git
    commit: b5d1d97b9ade902ab0fc67e8dc1b6959fe8e62a1 
  subdirs:
  - tensorflow
  - tensorflow-ops
  - tensorflow-core-ops
  - tensorflow-logging
  - tensorflow-proto
  - tensorflow-opgen
  - tensorflow-test
  - tensorflow-mnist
  - tensorflow-mnist-input-data
  extra-dep: true
- .
extra-deps:
- filepath-1.4.1.2
- proto-lens-0.2.2.0
- proto-lens-descriptors-0.2.2.0
- proto-lens-protobuf-types-0.2.2.0
- proto-lens-protoc-0.2.2.3
- snappy-0.2.0.2
- snappy-framing-0.1.1
- tensorflow-records-0.1.0.0
- tensorflow-records-conduit-0.1.0.0
resolver: lts-9.13
